spring:
  application:
    name: void

  data:
    redis:
      host: localhost
      port: 6379
gemini:
  api:
    key: ${KEY_hackerton}

springdoc:
  api-docs:
    version: openapi_3_0
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: false